CERES-396 Added the actuator endpoints to the QueryController.
racker/ceres pull request #35
Opened 2021-03-30 16:04 UTC by rajeshdasi

# Resolves

https://jira.rax.io/browse/CERES-396

# What

This Jira ticket adds an actuator meter for the query API with which it would be possible to see what time ranges users tend to query and then configure the downsample widths and retention accordingly.

## How to test

To verify this Jira start the Ceres application locally and make a request to http://localhost:8081/actuator/prometheus once the request is successful, one should be able to see the response with the following text.

Ceres_QueryApi_total{Query="With_Aggregator",} 0.0
Ceres_QueryApi_total{Query="Without_Aggregator",} 0.0

2021-03-31 14:41 UTC, matsboman reviewed
Some naming confusion

2021-03-31 14:41 UTC, matsboman commented on src/main/java/com/rackspace/ceres/app/web/QueryController.java
> +    aggregatorCounter = meterRegistry.counter("Ceres.QueryApi", "Query", "Without_Aggregator");
maybe `aggregatorCounter` => `noAggregatorQueryCounter` ?

2021-03-31 14:41 UTC, matsboman commented on src/main/java/com/rackspace/ceres/app/web/QueryController.java
> +    queryCounter = meterRegistry.counter("Ceres.QueryApi", "Query", "With_Aggregator");
maybe `queryCounter` => `aggregatorCounter` ?

2021-03-31 18:41 UTC, harageth submitted a review, later dismissed

2021-04-01 12:40 UTC, rohitsngh27 commented on src/main/java/com/rackspace/ceres/app/web/QueryController.java
> +    noAggregatorQueryCounter = meterRegistry.counter("Ceres.QueryApi", "Query", "Without_Aggregator");
name this one as `rawQueryCounter` and `meterRegistry.counter("ceres.query", "type", "raw")`

2021-04-01 12:41 UTC, rohitsngh27 commented on src/main/java/com/rackspace/ceres/app/web/QueryController.java
> +    aggregatorQueryCounter = meterRegistry.counter("Ceres.QueryApi", "Query", "With_Aggregator");
and this one as `downsampledQueryCounter` and meterRegistry.counter("ceres.query", "type", "downsample")

2021-04-01 12:42 UTC, rohitsngh27 requested changes
Few naming changes and also make changes in unit test cases to verify this counter is incremented.

2021-04-05 14:17 UTC, rohitsngh27 commented on src/test/java/com/rackspace/ceres/app/web/QueryControllerTest.java
> +    DownsampleProperties.class, MeterRegistryConfig.class})
Instead of using `MeterRegistryConfig` here you can simply add `SimpleMeterRegistry` here only.

2021-04-05 14:18 UTC, rohitsngh27 requested changes
Just some minor change and then it's good to go

2021-04-05 15:18 UTC, rohitsngh27 approved these changes

2021-04-05 16:08 UTC, shabd67 approved these changes

2021-04-05 16:09 UTC, merged